URL = "https://www.saucedemo.com/"
username_id = "user-name"
password_id = "password"
loginButton_id = "login-button"
invalidLogin = "data/pair4unlogin.xlsx"
errorWarning = "//div[@id='login_button_container']/div/form/div[3]/h3"
errorEmpty  = "//div[@class='error-message-container error']"
validLogin = "data/Kitap1.xlsx"
app_logo = "//div[@class='app_logo']"
errorLocked="//div[@class='error-message-container error']"